fm_elfinder:
    instances:
        default:
            locale: fr
            editor: custom # Très important : pas "ckeditor"
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'image/gif']
                        upload_deny: ['all']
                        upload_max_size: 5M



#fm_elfinder:
#    instances:
#        default:
#            locale: fr
#            editor: ckeditor
#            connector:
#                roots:
#                    uploads:
#                        driver: LocalFileSystem
#                        path: uploads
#                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'image/gif']
#                        upload_deny: ['all']
#                        upload_max_size: 10M

