# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    default_config: default
    configs:
        default:
            toolbar:
                - heading
                - bold
                - italic
                - link
                - blockQuote
                - imageUpload
                - insertTable
                - mediaEmbed
                - undo
                - redo
                - sourceEditing
                - htmlEmbed
            extraPlugins:
                - sourceediting
                - htmlEmbed
            removePlugins:
                - easyimage
                - autosave
            extraAllowedContent: '*[*]{*}(*)'
            allowedContent: true
            language: fr
            sourceEditing:
                allowedTags: [ 'h1', 'h2', 'h3', 'h4', 'p', 'div', 'span', 'a', 'img', 'ul', 'ol', 'li', 'table', 'tr', 'td', 'th', 'br', 'hr', 'strong', 'em', 'iframe', 'embed', 'object' ]
